Fix env_set_ok test and error message
fbcotter/py3nvml pull request #13
Opened 2020-04-13 17:51 UTC by JadHADDAD92

env_set_ok should raise error if set to True
and it should be set to False to avoid raising

2020-04-14 12:23 UTC, JadHADDAD92 commented
@fbcotter

2020-04-14 16:55 UTC, fbcotter requested changes
I see, there's a mismatch between the argument comment and the logic. My mistake. I'd prefer to change the comment though and keep this as it is. We should also change the default value to be False rather than True.

2020-04-14 18:31 UTC, JadHADDAD92 commented
should i change the parameter name as well? cause it's contradictory with its actual action now

2020-04-20 14:28 UTC, fbcotter approved these changes

2020-04-20 14:28 UTC, merged